[package]
name = "axum-next-app"
version = "0.1.0"
edition = "2021"
authors = ["SunsJay <sunsjay0806@gmail.com>"]
keywords = ["axum", "web", "database"]
license = "MIT"

[[bin]]
name = "app"
path = "crates/core/main.rs"
bench = false

[dependencies]
toml = "0.8"
serde = "1.0"
